### PR TITLE
fix for CONTENT_IGNORE cos try to replace already defined node with nil (fix #11)

### LINKED ISSUE #11: get CONTENT_IGNORE cos try to replace already defined node with nill
the usage of `minetest.set_node` in the `set_default_node `function try to replace the already node position (just AT ground) with the feeds of the player:

i received now this :
```
Oct 22 11:10:32 venenux minetestserver: 2021-10-22 11:10:32: [Server]: Wrote rspawn data with 3 pregen nodes
Oct 22 11:10:32 venenux minetestserver: 2021-10-22 11:10:32: [Server]: [rspawn] DEBUG : Returning pregenerated spawn :: {
Oct 22 11:10:32 venenux minetestserver: y = 12,
Oct 22 11:10:32 venenux minetestserver: x = -280,
Oct 22 11:10:32 venenux minetestserver: z = -258
Oct 22 11:10:32 venenux minetestserver: }
Oct 22 11:10:32 venenux minetestserver: 2021-10-22 11:10:32: [Server]: [rspawn] DEBUG : (-280,12,-258)
Oct 22 11:10:32 venenux minetestserver: 2021-10-22 11:10:32: [Server]: Wrote rspawn data with 3 pregen nodes
Oct 22 11:10:33 venenux minetestserver: 2021-10-22 11:10:33: ERROR[Server]: Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "default:dirt_with_snow" at (-280,11,-258) (block (-18,0,-17))
```

in the mos common sense @taikedz you're trying to replace air with an unknown block (the player foods ones) :laughing:  cos player is just AT ground level or "at block level" :

```
 local function set_default_node(pos)
     if rspawn.spawn_block then
         minetest.set_node(pos, {name=rspawn.spawn_block})
     end
 end
```

EDITED the problem was an undefined `rspawn.spawn_block` check comments adn given solution!

### PR DESCRIPTION
**Pull request by mckaygerhard**
with this not so ugly solution we have a working rspawn mod.. @taikedz  is currently working in venenux production server (currently subs.fusilsystem.com) from https://codeberg.org/minenux project

* check if the `rspawn.spawn_block` is defined and check if valid
* so then `rspawn.spawn_block` is used at `set_default_node` legally
* then `minetest.set_node(pos, {name=rspawn.spawn_block})` can work
* this closes closed https://github.com/taikedz-mt/rspawn/issues/11

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -35,6 +35,11 @@ dofile(mpath.."/lua/forceload.lua")
 dofile(mpath.."/lua/debugging.lua")
 
 
+minetest.after(0,function()
+    if not minetest.registered_items[rspawn.spawn_block] then
+        rspawn.spawn_block = "default:dirt_with_grass"
+    end
+end)
```
Comment (taikedz) [inline init.lua:42]: This is a decent safe guard ; however perhaps setting this line by default instead would help?

https://github.com/taikedz-mt/rspawn/blob/master/settingtypes.txt#L7

**Review by taikedz — COMMENTED** [review]
Your code is fine to go in as-is , but before that I just wanted to highlight the possibility of simply setting the default value up-front, instead of additional code?

I'm happy either way.

File: init.lua [hunk 2]
```diff
@@ -21,7 +21,7 @@ rspawn.kick_on_fail = minetest.settings:get_bool("rspawn.kick_on_fail") == true
 rspawn.max_pregen_spawns = tonumber(minetest.settings:get("rspawn.max_pregen") or 5)
 rspawn.search_radius = tonumber(minetest.settings:get("rspawn.search_radius") or 32)
 rspawn.gen_frequency = tonumber(minetest.settings:get("rspawn.gen_frequency") or 30)
-rspawn.spawn_block = minetest.settings:get("rspawn.spawn_block")
+rspawn.spawn_block = minetest.settings:get("rspawn.spawn_block") or "default:dirt_with_grass"
```
Comment (mckaygerhard) [inline init.lua:24]: @taikedz  i already made it here!

File: init.lua (hunk 1 above)
Comment (mckaygerhard) [reply init.lua:42]: as i commented **i already made it .. see lines before**..  that is need **when the setted value are wrong from user.. cos it produces the conecnt ignore also**

Comment (taikedz) [reply init.lua:42]: Yes, but I meant specifically in the `settingtypes.txt` file - see line 8, where you can actually add a value 😀

**Review by taikedz — APPROVED** [review]
As said before, a fair change. Merging and closing.

File: init.lua (hunk 1 above)
Comment (mckaygerhard) [reply init.lua:42]: ahhh ok ok i set that as hint for how to set a value
